### PR TITLE
Fix logic around responding with mentions

### LINKED ISSUE #127: Responding to a message context causes a null assertion on allowedMentions.
**Describe the bug**
See the title.

**To Reproduce**
Use a text command and context.respond.

**Expected behavior**
The response should work.

**Desktop (please complete the following information):**
 - OS: Linux
 - Dart version: 3.1.2
 - Nyxx version: 6.0.0-dev.3
 - nyxx_commands version: 6.0.0-dev.1

### PR DESCRIPTION
**Pull request by abitofevrything**
# Description

Closes #127

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] Ran `dart analyze .`
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: lib/src/util/mixins.dart [hunk 1]
```diff
@@ -819,10 +819,13 @@ mixin MessageRespondMixin implements InteractiveMixin {
...
-      // non-null, in which case we want to change it. Otherwise, this does nothing.
-      builder.allowedMentions!.parse =
-          {...(builder.allowedMentions!.parse ?? <String>[]), 'replied_user'}.toList();
+      if (level.mention == true) {
+        builder.allowedMentions =
+            (builder.allowedMentions ?? AllowedMentions()) | AllowedMentions(repliedUser: true);
+      } else if (level.mention == false) {
+        builder.allowedMentions =
+            (builder.allowedMentions ?? AllowedMentions()) & AllowedMentions(repliedUser: false);
+      }
```
Comment (l7ssha) [inline lib/src/util/mixins.dart:828]: is == needed? cant if be if(level.mention) {} else {} ?

**Review by l7ssha — CHANGES_REQUESTED** [review]

File: lib/src/util/mixins.dart (hunk 1 above)
Comment (abitofevrything) [reply lib/src/util/mixins.dart:828]: `mention` is nullable and if null, we want to leave `allowedMentions` as-is, so we only check for non-null values.

Comment (Rapougnac) [reply lib/src/util/mixins.dart:828]: Maybe something like this would be less verbose
```dart
if (level.mention case bool m) {
  final allowedMentions = builder.allowedMentions ?? AllowedMentions();
  final mentions = AllowedMentions(repliedUser: m);
  builder.allowedMentions = m ? (allowedMentions & mentions) : (allowedMentions | mentions);
}
```

Comment (l7ssha) [reply lib/src/util/mixins.dart:828]: @Rapougnac sugesstion is slightly better. WOuld name m variable a little bit better - `levelMention`

**Review by l7ssha — APPROVED** [review]
